export const kodeNopol: {kode: string, wilayah: string}[] = [
  { kode: "A", wilayah: "Banten" },
  { kode: "B", wilayah: "DKI Jakarta" },
  { kode: "D", wilayah: "Bandung" },
  { kode: "E", wilayah: "Cirebon" },
  { kode: "F", wilayah: "Bogor" },
  { kode: "G", wilayah: "Pekalongan" },
  { kode: "H", wilayah: "Semarang" },
  { kode: "K", wilayah: "Pati" },
  { kode: "L", wilayah: "Surabaya" },
  { kode: "M", wilayah: "Madura" },
  { kode: "N", wilayah: "Malang" },
  { kode: "P", wilayah: "Besuki" },
  { kode: "R", wilayah: "Banyumas" },
  { kode: "S", wilayah: "Bojonegoro" },
  { kode: "T", wilayah: "Karawang" },
  { kode: "AA", wilayah: "Kedu" },
  { kode: "AB", wilayah: "DI Yogyakarta" },
  { kode: "AD", wilayah: "Surakarta" },
  { kode: "AE", wilayah: "Madiun" },
  { kode: "AG", wilayah: "Kediri" },
  { kode: "BA", wilayah: "Sumatera Barat" },
  { kode: "BB", wilayah: "Sumatera Utara Barat" },
  { kode: "BD", wilayah: "Bengkulu" },
  { kode: "BE", wilayah: "Lampung" },
  { kode: "BG", wilayah: "Sumatera Selatan" },
  { kode: "BH", wilayah: "Jambi" },
  { kode: "BK", wilayah: "Sumatera Utara Timur" },
  { kode: "BL", wilayah: "Aceh" },
  { kode: "BM", wilayah: "Riau" },
  { kode: "BN", wilayah: "Bangka Belitung" },
  { kode: "BP", wilayah: "Kepulauan Riau" },
  { kode: "DA", wilayah: "Kalimantan Selatan" },
  { kode: "DB", wilayah: "Sulawesi Utara Daratan" },
  { kode: "DC", wilayah: "Sulawesi Barat" },
  { kode: "DD", wilayah: "Sulawesi Selatan" },
  { kode: "DE", wilayah: "Maluku" },
  { kode: "DG", wilayah: "Maluku Utara" },
  { kode: "DH", wilayah: "NTT Timor" },
  { kode: "DK", wilayah: "Bali" },
  { kode: "DL", wilayah: "Sulawesi Utara Kepulauan" },
  { kode: "DN", wilayah: "Sulawesi Tengah" },
  { kode: "DP", wilayah: "Sulawesi Selatan Utara" },
  { kode: "DR", wilayah: "NTB Lombok" },
  { kode: "DT", wilayah: "Sulawesi Tenggara" },
  { kode: "DW", wilayah: "Sulawesi Selatan Bone" },
  { kode: "EA", wilayah: "NTB Sumbawa" },
  { kode: "EB", wilayah: "NTT Flores" },
  { kode: "ED", wilayah: "NTT Sumba" },
  { kode: "KB", wilayah: "Kalimantan Barat" },
  { kode: "KH", wilayah: "Kalimantan Tengah" },
  { kode: "KT", wilayah: "Kalimantan Timur" },
  { kode: "KU", wilayah: "Kalimantan Utara" },
  { kode: "PA", wilayah: "Papua" },
  { kode: "PB", wilayah: "Papua Barat" }
];